container:
  image: node:latest

lint_task:
  environment:
    NPM_TOKEN: ENCRYPTED[455aadd99bc5eff9e6e64b5271b53470cdf775e9ce621c17f0bdfd917b5bce4fcfdf9447ded59d2a79e6b02378ca7f4a]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  install_script: npm install
  test_script: npm run lint

test_task:
  environment:
    NPM_TOKEN: ENCRYPTED[455aadd99bc5eff9e6e64b5271b53470cdf775e9ce621c17f0bdfd917b5bce4fcfdf9447ded59d2a79e6b02378ca7f4a]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  install_script: npm install
  test_script: npm test

coverage_task:
  env:
    NPM_TOKEN: ENCRYPTED[455aadd99bc5eff9e6e64b5271b53470cdf775e9ce621c17f0bdfd917b5bce4fcfdf9447ded59d2a79e6b02378ca7f4a]
    CODECOV_TOKEN: ENCRYPTED[cc9756d1a2adf5cc000b12cbf976eeeea9442237b5288f81b5279d23322c6e1f6deb2d4898c60e77f239a218b8ee7fcf]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  depends_on:
    - lint_task
    - test_task
  only_if: $BRANCH == "master"
  environment:
    NPM_TOKEN: ENCRYPTED[455aadd99bc5eff9e6e64b5271b53470cdf775e9ce621c17f0bdfd917b5bce4fcfdf9447ded59d2a79e6b02378ca7f4a]
  script:
    - printf "//`node -p \"require('url').parse('https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
    - npm install
    - npm run build
#    - npx semantic-release
    - npm publish --access public